#!/usr/bin/env bash
# clean_smoke_test.sh
#
# Remove all outputs generated by run_smoke_test.sh.
# Run this after verifying the smoke test completed successfully.
#
# Usage:
#   bash clean_smoke_test.sh

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "Removing smoke test outputs..."

rm -rf smoke_test_results/
rm -rf asd_unsup_runs/

echo ""
echo "Smoke test outputs removed."
echo ""
echo "NOTE: smoke_test_abide100.pkl (if present) is kept; (re-)create it with create_smoke_test.py from your own ABIDE pickle if needed."
